### ISSUE TITLE
update regex-replace to update the Kotlin generator versions

### ISSUE THREAD

**Issue by stevehu** [networknt/light-config-test#310]

**Comment by fredriv** [comment]
It seems the regex pattern here is wrong, as it is testing for a pom.xml style variable in gradle.properties: https://github.com/networknt/light-config-test/blob/master/light-bot/version-upgrade/1_6_x/upgrade-all/config/version-upgrade.yml#L110
Should probably be something like `light4jVersion=...` instead.

In addition, there is no configuration for updating gradleProperties.rocker.raw in the version upgrade config in light-bot: https://github.com/networknt/light-bot/blob/master/bot-cli/src/main/resources/config/version-upgrade.yml#L81-L86

**Comment by fredriv** [comment]
Also I guess my PRs for the other issue earlier should have used the SNAPSHOT versions instead of the latest release versions? Otherwise it won't be picked up by the version upgrade command?

**Comment by stevehu** [comment]
@fredriv You are right. That is the reason the Kotlin templates are not updated correctly. Yes. The latest SNAPSHOT version should be used. We have a release process to update SNAPSHOT version to release version just before release and update to the next SNAPSHOT version after release. We also release the SNAPSHOT version to the maven central to help our platform developers to avoid building everything on their local. Do you want to take a look at this issue? Thanks.

**Comment by fredriv** [comment]
Sure, I can have a go at it :)

**Comment by fredriv** [comment]
Submitted a PR. Not sure if this config affects the real release process though, or if that is located somewhere else?
